# -*- coding: utf-8 -*-
"""ImageProcess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11zILX_5m59DbIEdii_jhnvu2_UJBgBZr

## 影像讀取及資料增強 - OpenCV
### 使用OpenCV讀取影像
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

image_path = 'D:/cat.jpg'
image_folder = 'D:/cat/'

image = cv2.imread(image_path, cv2.IMREAD_COLOR)

image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.imshow(image)
plt.show()

from google.colab import drive
drive.mount('/content/drive')

import cv2
import numpy as np
from matplotlib import pyplot as plt

image_path = '/content/drive/Shared drives/1082_MedImg_workshop/A團隊/data/TRAIN'

image = cv2.imread(image_path, cv2.IMREAD_COLOR)

image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

plt.imshow(image_gray, 'gray')

plt.show()

"""### OpenCV – 平移圖片"""

image = cv2.imread(image_path ,cv2.IMREAD_COLOR)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

func = np.float32([[1, 0, 50],   #向左或向右平移 
                   [0, 1, -100]])  #下上或向下平移
shifted = cv2.warpAffine(image, func, (image.shape[1], image.shape[0]))

plt.imshow(shifted)
plt.show()

"""### OpenCV – 旋轉圖片"""

image = cv2.imread(image_path ,cv2.IMREAD_COLOR)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

h, w, _ = image.shape
center = (w//2, h//2)

func = cv2.getRotationMatrix2D(center, 50, 0.6)
rotated = cv2.warpAffine(image, func, (w, h))

plt.imshow(rotated)
plt.show()

"""### OpenCV – 翻轉圖片"""

original_img = cv2.imread(image_path ,cv2.IMREAD_COLOR)
original_img = cv2.cvtColor(original_img, cv2.COLOR_BGR2RGB)

horizontal_img = cv2.flip(original_img, 1)
vertical_img = cv2.flip(original_img, -1)

images = [original_img, horizontal_img, vertical_img]
plt.figure(figsize=(12, 12))
for i in range(3):
    plt.subplot(1,3,i+1)
    plt.imshow(images[i],'gray')

plt.show()

"""## 影像讀取及資料增強 - Keras
### 資料擴增 Keras - ImageDataGenerator
### 資料讀取 Keras - flow_from_directory
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tensorflow.keras.preprocessing.image import ImageDataGenerator

"""### 使用matplot顯示影像"""

def img_plot(x_data, batch_size=4):
    plt.figure(figsize=(12, 6))
    for i in range(batch_size):
        plt.subplot(1, 4, i+1)
        plt.imshow(x_data[i].astype('uint8'))
    plt.show()

"""### Keras – 水平/垂直翻轉圖片"""

data_datagen = ImageDataGenerator(horizontal_flip=True,
                                  vertical_flip=False)

data_generator = data_datagen.flow_from_directory('D:/animal',
                                                  target_size=(255, 255),
                                                  batch_size=4,
                                                  class_mode='categorical')
data_generator.class_indices

images, labels = data_generator.next()
img_plot(images)

"""### Keras – 旋轉(Rotation)圖片"""

data_datagen = ImageDataGenerator(rotation_range=90,
                                  fill_mode='constant')

data_generator = data_datagen.flow_from_directory('D:/animal',
                                                  target_size=(255, 255),
                                                  batch_size=4,
                                                  class_mode='categorical')
images, labels = data_generator.next()
img_plot(images)

"""### Keras – 剪裁(shear)圖片"""

data_datagen = ImageDataGenerator(shear_range=60,
                                  width_shift_range=0.3,
                                  fill_mode='constant')

data_generator = data_datagen.flow_from_directory('D:/animal',
                                                  target_size=(255, 255),
                                                  batch_size=4,
                                                  class_mode='categorical')
images, labels = data_generator.next()
img_plot(images)

"""### Keras – 平移(shift)圖片"""

data_datagen = ImageDataGenerator(width_shift_range=0.2,
                                  height_shift_range=0.1,
                                  fill_mode='constant')

data_generator = data_datagen.flow_from_directory('D:/animal',
                                                  target_size=(255, 255),
                                                  batch_size=4,
                                                  class_mode='categorical')
images, labels = data_generator.next()
img_plot(images)

"""### Keras – 放大縮小(zoom)圖片"""

data_datagen = ImageDataGenerator(zoom_range=[0.5, 1],
                                  fill_mode='constant',
                                  cval=255)

data_generator = data_datagen.flow_from_directory('D:/animal',
                                                  target_size=(255, 255),
                                                  batch_size=4,
                                                  class_mode='categorical')
images, labels = data_generator.next()
img_plot(images)



